# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPassenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_purchased', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FlightPassengers',
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zad2.Plane'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightpassenger',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zad2.Flight'),
        ),
        migrations.AddField(
            model_name='flightpassenger',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zad2.Person'),
        ),
    ]
