# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0002_auto_20180506_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='places',
        ),
    ]
