# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0003_remove_plane_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='places',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
