# Generated by Django 2.0.4 on 2018-05-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0005_auto_20180518_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='start_hour',
            field=models.IntegerField(blank=True, default=12),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
