# Generated by Django 2.0.4 on 2018-05-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0006_auto_20180518_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='end_hour',
            field=models.IntegerField(blank=True, default=12),
        ),
        migrations.AddField(
            model_name='flight',
            name='end_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
