# Generated by Django 2.0.4 on 2018-05-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0007_auto_20180518_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='end_minutes',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='start_minutes',
        ),
        migrations.AlterField(
            model_name='flight',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
