# Generated by Django 2.0.4 on 2018-06-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0010_auto_20180601_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='crew',
        ),
    ]
