# Generated by Django 2.0.4 on 2018-06-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0011_remove_plane_crew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaneCrew',
        ),
    ]
