# Generated by Django 2.0.4 on 2018-06-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0018_plane_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='planecrew',
            name='crew_id',
        ),
    ]
