# Generated by Django 2.0.4 on 2018-06-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0020_plane_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='plane',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='crew',
        ),
    ]
