# Generated by Django 2.0.4 on 2018-06-01 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0021_auto_20180601_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zad2.Plane'),
        ),
    ]
