# Generated by Django 2.0.4 on 2018-06-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0023_plane_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='crew',
        ),
    ]
