# Generated by Django 2.0.4 on 2018-06-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0025_plane_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanesCrews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejestration_number', models.CharField(max_length=30)),
                ('places', models.IntegerField()),
                ('crew', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zad2.PlaneCrew')),
            ],
        ),
        migrations.RemoveField(
            model_name='plane',
            name='crew',
        ),
    ]
