# Generated by Django 2.0.4 on 2018-06-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0026_auto_20180602_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew_first_name',
            field=models.CharField(default='Mateusz', max_length=30),
        ),
        migrations.AddField(
            model_name='flight',
            name='crew_last_name',
            field=models.CharField(default='Masiak', max_length=30),
        ),
    ]
