# Generated by Django 2.0.4 on 2018-06-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad2', '0027_auto_20180608_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
